# Generated by Django 4.1.5 on 2023-01-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercosts',
            old_name='data',
            new_name='date',
        ),
    ]
