# Generated by Django 4.1.5 on 2023-01-08 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_alter_othercosts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_from',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('store', 'store'), ('site', 'online')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='othercosts',
            name='user',
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('text', models.CharField(blank=True, max_length=255)),
                ('category', models.ManyToManyField(to='web.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.IntegerField()),
                ('rial', models.BigIntegerField()),
                ('lir', models.IntegerField()),
                ('order', models.ManyToManyField(to='web.orders')),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('text', models.CharField(blank=True, max_length=255)),
                ('buy_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.buy_from')),
                ('change', models.ManyToManyField(to='web.changes')),
                ('order', models.ManyToManyField(to='web.orders')),
            ],
        ),
        migrations.AddField(
            model_name='othercosts',
            name='order',
            field=models.ManyToManyField(to='web.orders'),
        ),
    ]
