# Generated by Django 4.1.5 on 2023-01-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_buy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='followCode',
            field=models.CharField(auto_created=True, default=61326734, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
